/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jogo.view;

import com.jogo.entity.Usuario;
import com.jogo.telasplash.Batman;
import com.jogo.telasplash.CapitaoAmerica;
import com.jogo.telasplash.CronicNarnia;
import com.jogo.telasplash.HarryPotter;
import com.jogo.telasplash.InstumentosMortais;
import com.jogo.telasplash.SenhorAneis;
import com.jogo.telasplash.Varios;
import com.jogo.telasplash.VelozesFuriosos;
import java.awt.Toolkit;

/**
 *
 * @author Mizael
 */
public class Categoria extends javax.swing.JFrame {

    /**
     * Creates new form Categoria
     */
    private Usuario usuario;
    
    public Categoria(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        ClassLoader loader = getClass().getClassLoader();
        setIconImage(Toolkit.getDefaultToolkit().createImage(loader.getResource("folder/ranked2.png")));
    }

    private Categoria() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCapitaoAmer = new javax.swing.JButton();
        btnSenhoAneis = new javax.swing.JButton();
        btnBatman = new javax.swing.JButton();
        btnVeloFuri = new javax.swing.JButton();
        btnHarryPotter = new javax.swing.JButton();
        btnIntruMortais = new javax.swing.JButton();
        btnCronicNarnia = new javax.swing.JButton();
        btnVarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 225));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escolha uma categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 310, 50));

        btnCapitaoAmer.setText("Capitao America");
        btnCapitaoAmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapitaoAmerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapitaoAmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 160, -1));

        btnSenhoAneis.setText("O Senhor dos Anéis");
        btnSenhoAneis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhoAneisActionPerformed(evt);
            }
        });
        getContentPane().add(btnSenhoAneis, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));

        btnBatman.setText("Batman");
        btnBatman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatmanActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatman, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        btnVeloFuri.setText("Velozes e Furiosos");
        btnVeloFuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeloFuriActionPerformed(evt);
            }
        });
        getContentPane().add(btnVeloFuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, -1));

        btnHarryPotter.setText("Harry Potter");
        btnHarryPotter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarryPotterActionPerformed(evt);
            }
        });
        getContentPane().add(btnHarryPotter, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 160, -1));

        btnIntruMortais.setText("Os Instumentos Mortais");
        btnIntruMortais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntruMortaisActionPerformed(evt);
            }
        });
        getContentPane().add(btnIntruMortais, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, -1));

        btnCronicNarnia.setText("As Cronicas de Narnia");
        btnCronicNarnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCronicNarniaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCronicNarnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 160, -1));

        btnVarios.setText("Varios");
        btnVarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/batmam.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapitaoAmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapitaoAmerActionPerformed
        // TODO add your handling code here:
        CapitaoAmerica capitaoAmerica = new CapitaoAmerica(usuario);
        capitaoAmerica.setVisible(true);
        capitaoAmerica.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCapitaoAmerActionPerformed

    private void btnSenhoAneisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhoAneisActionPerformed
        // TODO add your handling code here:
        SenhorAneis senhorAneis = new SenhorAneis(usuario);
        senhorAneis.setVisible(true);
        senhorAneis.setLocationRelativeTo(null);
        this.dispose();
  
    }//GEN-LAST:event_btnSenhoAneisActionPerformed

    private void btnBatmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatmanActionPerformed
        // TODO add your handling code here:
        Batman batman = new Batman(usuario);
        batman.setVisible(true);
        batman.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBatmanActionPerformed

    private void btnVeloFuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeloFuriActionPerformed
        // TODO add your handling code here:
        VelozesFuriosos veloFuri = new VelozesFuriosos(usuario);
        veloFuri.setVisible(true);
        veloFuri.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVeloFuriActionPerformed

    private void btnHarryPotterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarryPotterActionPerformed
        // TODO add your handling code here:
        HarryPotter harryPotter = new HarryPotter(usuario);
        harryPotter.setVisible(true);
        harryPotter.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHarryPotterActionPerformed

    private void btnIntruMortaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntruMortaisActionPerformed
        // TODO add your handling code here:
        InstumentosMortais intruMortais = new InstumentosMortais(usuario);
        intruMortais.setVisible(true);
        intruMortais.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnIntruMortaisActionPerformed

    private void btnCronicNarniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCronicNarniaActionPerformed
        // TODO add your handling code here:
        CronicNarnia cronicNarnia = new CronicNarnia(usuario);
        cronicNarnia.setVisible(true);
        cronicNarnia.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCronicNarniaActionPerformed

    private void btnVariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVariosActionPerformed
        // TODO add your handling code here:
        Varios varios = new Varios(usuario);
        varios.setVisible(true);
        varios.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatman;
    private javax.swing.JButton btnCapitaoAmer;
    private javax.swing.JButton btnCronicNarnia;
    private javax.swing.JButton btnHarryPotter;
    private javax.swing.JButton btnIntruMortais;
    private javax.swing.JButton btnSenhoAneis;
    private javax.swing.JButton btnVarios;
    private javax.swing.JButton btnVeloFuri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
